from typing import Any, Protocol

class Prediction:
    code: str
    signature: str
    architecture: str
    is_valid: bool
    errors: Any

class Example:
    def __init__(self, **fields: Any) -> None: ...
    def with_inputs(self, *fields: str) -> Example: ...

class Module(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class Signature: ...

def InputField(desc: str = ...) -> Any: ...
def OutputField(desc: str = ...) -> Any: ...

def Predict(signature: Any) -> Module: ...
def ChainOfThought(signature: Any) -> Module: ...

class GEPA:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def compile(self, module: Module, trainset: list[Example], valset: list[Example]) -> Module: ...
